[package]
name = "hook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hook-raft = { path = "../.." }
tokio = { version = "1.17", features = ["full"] }
